# Generated by Django 3.0.5 on 2020-04-15 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of release'),
            preserve_default=False,
        ),
    ]
